product.property= Product Profile Dev

#Crear  de la base de datos
#spring.data.mongodb.uri=mongodb://localhost:27017/productdb
#spring.profiles.active=dev
app.testPropiedad= Propiedad de Prueba By: Jimmy Delgado 3ra version

server.port=0

#para un nombre unicos
eureka.instance.instance-id=${spring.application.name}:${random.uuid}